'use client';

import Link from 'next/link';
import { ReactNode, useMemo, useState } from 'react';

type Category =
  | 'Planning Your Safari' | 'Accommodation' | 'Safari Vehicles & Transport'
  | 'Wildlife & Game Drives' | 'Health Safety & Insurance' | 'Payments & Booking'
  | 'Travel Documents & Visas' | 'Packing & Luggage' | 'Family & Special Needs'
  | 'Kenya Coast & Beach' | 'Nairobi National Park' | 'Gorilla Trekking' | 'Mountain Climbing';

type FAQ = { category: Category; question: string; answer: ReactNode };
const A = ({ href, children }: { href: string; children: ReactNode }) => <Link href={href} className="text-[var(--golden-savannah)] underline decoration-transparent underline-offset-4 transition hover:decoration-current">{children}</Link>;

const faqs: FAQ[] = [
  { category: 'Planning Your Safari', question: 'When is the best time for a Kenya safari?', answer: <>Kenya is rewarding year-round. July to October is dry, with shorter grass and the Masai Mara portion of the wildebeest migration; January to March is excellent for clear skies and young wildlife. April–May and November are greener, quieter and often better value. We match rainfall, school holidays and your target parks on <A href="/kenya-safaris">Kenya safari</A> planning.</> },
  { category: 'Planning Your Safari', question: 'How many days do I need for an East Africa safari?', answer: <>Three days works for a focused Masai Mara, Amboseli or Tsavo escape. Seven to nine days allows two or three parks without rushing; 10–14 days can combine Kenya, a Tanzania safari, beach time and a slower pace. Driving distances and flight timings shape every itinerary.</> },
  { category: 'Planning Your Safari', question: 'Can Collective African Tours & Safaris create a tailor-made itinerary?', answer: <>Yes. With 15 years of regional operating experience, we build private journeys around dates, budget, interests, mobility and preferred accommodation. Combine a <A href="/kenya-tanzania-safaris">Kenya and Tanzania safari</A>, culture, photography, beach or climbing rather than fitting your trip to a fixed departure.</> },
  { category: 'Planning Your Safari', question: 'Are international flights included in safari prices?', answer: <>International flights are normally excluded, allowing you to select the best routing and fare from home. We can advise on arrival times into Nairobi’s Jomo Kenyatta International Airport (JKIA), arrange regional connections and help with <A href="/flights">flight planning</A>.</> },
  { category: 'Planning Your Safari', question: 'What weather should I expect by month?', answer: <>Nairobi and the highlands are cool at dawn year-round; June–August mornings can feel close to 10°C. Long rains usually fall April–May, short rains around November, while December–March and June–October are generally drier. Rain is rarely all-day and brings dramatic skies, fresh grazing and outstanding birdlife.</> },
  { category: 'Accommodation', question: 'What is the difference between a safari lodge and a tented camp?', answer: <>A safari lodge usually has permanent rooms, substantial public spaces and sometimes pools or spas. A tented camp has canvas walls, proper beds and ensuite bathrooms but a closer connection to night sounds and the landscape. Both can be intimate, secure and exceptionally comfortable.</> },
  { category: 'Accommodation', question: 'What do Economy, Comfort, Luxury and Superior Luxury mean?', answer: <>Economy prioritises clean, well-run accommodation and value; Comfort adds character, stronger locations and amenities; Luxury brings high service, refined dining and exclusive settings; Superior Luxury is our most exceptional camp and lodge selection, often with private guides, premium inclusions and standout views. We explain the exact property, not just a label.</> },
  { category: 'Accommodation', question: 'What are room occupancy limits on safari?', answer: <>Most standard rooms or tents take a maximum of three guests, commonly a double/twin plus one extra bed. Larger families should request family tents, interconnecting rooms or private houses early; availability is limited in popular Masai Mara and Amboseli camps.</> },
  { category: 'Accommodation', question: 'What is a single supplement?', answer: <>It is the additional cost charged by many properties when one traveller occupies a room or tent alone. It covers the unused bed and fixed room costs. Some safari lodges waive it in selected green-season dates, so ask us to check before confirming.</> },
  { category: 'Accommodation', question: 'Is WiFi available at safari lodges?', answer: <>Most lodges offer WiFi in lounges or rooms, but speed varies with remoteness and weather. Do not expect reliable streaming in a tented camp. This is intentional in some wilderness areas; a Kenyan SIM provides a useful backup where signal exists.</> },
  { category: 'Safari Vehicles & Transport', question: 'What vehicles do you use on game drives?', answer: <>Our standard vehicle is a pop-up-top 4x4 Toyota Land Cruiser, carrying a maximum of six passengers for a window seat and room to photograph. Vehicles carry a cooler, drinking water, first-aid kit, radio communication and experienced safari driver-guide; see <A href="/transport-solutions">transport solutions</A>.</> },
  { category: 'Safari Vehicles & Transport', question: 'Are open safari vehicles available for photographers?', answer: <>Yes, selected conservancies and private areas permit open-sided vehicles, ideal for unobstructed low-angle photography. They are not suitable everywhere or in every weather condition, and reserve rules often require enclosed vehicles. Tell us your lens, subjects and season so we can reserve the right setup.</> },
  { category: 'Safari Vehicles & Transport', question: 'How long are the drives from Nairobi to Masai Mara and Amboseli?', answer: <>Nairobi to the Masai Mara is approximately 5–6 hours by road, including comfort stops, depending on your gate and camp. Nairobi to Amboseli is about 4–5 hours. A <A href="/kenya-flight-safaris">fly-in safari</A> reduces each to roughly a one-hour flight plus airstrip transfer.</> },
  { category: 'Safari Vehicles & Transport', question: 'Can you arrange JKIA transfers, domestic flights and private charters?', answer: <>Yes. We meet guests at JKIA, transfer between hotels and Wilson Airport, book scheduled bush flights and can quote private charters. A representative monitors the agreed arrival details; share flight changes promptly so we can adjust your pickup.</> },
  { category: 'Safari Vehicles & Transport', question: 'What is the SGR train and how do I book it?', answer: <>The Madaraka Express SGR links Nairobi Terminus and Mombasa Terminus, with transfers needed to city hotels and beach resorts. First class offers more space and is popular for the coast route. Book directly through <a href="https://krc.co.ke" target="_blank" rel="noreferrer" className="text-[var(--golden-savannah)] underline hover:decoration-transparent">Kenya Railways</a>; we can arrange the connecting transfer.</> },
  { category: 'Safari Vehicles & Transport', question: 'Is the SGR train safe and comfortable?', answer: <>Yes. It is a modern, scheduled passenger service with controlled station access, luggage screening and onboard staff. Arrive early, keep passports, valuables and medication with you, and use only arranged transfers at either terminus. Daylight travel also gives views across Tsavo country.</> },
  { category: 'Safari Vehicles & Transport', question: 'What are the advantages of a fly-in safari?', answer: <>Fly-in safaris save long road days, place you near remote camps and preserve energy for game drives. They are ideal for short stays, honeymoons and multi-country itineraries. Soft luggage limits apply, but the time saved between Nairobi, the Mara, Samburu and the coast can be transformative.</> },
  { category: 'Wildlife & Game Drives', question: 'What does “unlimited game drives” mean?', answer: <>On a private safari, your vehicle is dedicated to your party and the guide adapts drives to wildlife sightings, within park rules and your camp schedule. Most parks permit driving roughly 6:30am–6pm; it does not mean driving after official closing or off-road where prohibited.</> },
  { category: 'Wildlife & Game Drives', question: 'Can I see the Big Five in Kenya?', answer: <>Chances are excellent but never guaranteed. Amboseli is famed for elephant herds; Lake Nakuru and Ol Pejeta are strong for rhinos; Masai Mara is superb for lions, leopards and cheetahs; buffalo are widespread. Your guide reads tracks, radio reports and seasonal movement rather than promising wildlife.</> },
  { category: 'Wildlife & Game Drives', question: 'Masai Mara Reserve or conservancy: which should I choose?', answer: <>The Reserve delivers classic migration crossings and broad plains; neighbouring conservancies are less crowded and may allow night drives, bush walks and off-road viewing under their own rules. Combining both offers variety. Conservancy fees and vehicle limits differ from the Reserve.</> },
  { category: 'Wildlife & Game Drives', question: 'When is the Great Wildebeest Migration in Masai Mara?', answer: <>Herds commonly reach the Mara ecosystem from Tanzania’s Serengeti between July and October, but rains dictate the exact timing and river crossings cannot be scheduled. The spectacle is more than crossings: zebras, gazelles, predators and vast moving herds make this a remarkable <A href="/tanzania-safaris">Tanzania safari</A> and Kenya experience.</> },
  { category: 'Wildlife & Game Drives', question: 'Can we do night game drives and bush walks?', answer: <>Night drives and guided bush walks are generally available only in private conservancies, not Kenya’s national parks or the Masai Mara National Reserve. They reveal aardvark, genet, owls, tracks and smaller ecology. Activities use specialist guides and minimum-age rules may apply.</> },
  { category: 'Wildlife & Game Drives', question: 'Which parks are best for bird watching?', answer: <>Lake Naivasha and Lake Nakuru reward waterbird enthusiasts, Kakamega Forest has forest specials, Samburu offers arid-country species, and Amboseli’s wetlands attract waterbirds beneath Kilimanjaro. Nairobi National Park alone records more than 400 bird species. Bring a field guide and tell your guide your target list.</> },
  { category: 'Wildlife & Game Drives', question: 'Can you arrange balloon safaris, bush dining and cultural visits?', answer: <>Yes. Masai Mara balloon flights launch before dawn, followed by a bush breakfast, subject to weather. We also arrange sundowners, private bush meals and respectful Maasai community visits where tourism revenue is locally agreed. Advance booking is essential in migration season.</> },
  { category: 'Wildlife & Game Drives', question: 'How do photography safaris work?', answer: <>We plan around light, species behaviour and patience: private vehicles, no more than six guests per Land Cruiser, flexible stops and optional open vehicles in suitable conservancies. Bring spare batteries, dust protection and lenses from wide angle to 400mm+; guides position responsibly without disturbing animals.</> },
  { category: 'Health Safety & Insurance', question: 'Is travel insurance required?', answer: <>Comprehensive travel insurance is strongly required before travel: it should cover medical care, emergency evacuation, cancellation, baggage and activities such as gorilla trekking or mountain climbing if included. Evacuation cover matters in remote parks. Read exclusions and carry your insurer’s emergency number.</> },
  { category: 'Health Safety & Insurance', question: 'Do I need malaria medication or a yellow fever vaccination?', answer: <>Consult a qualified travel clinic well before departure. Malaria risk varies by location and season; prophylaxis, repellent, long sleeves at dusk and nets are useful precautions. Yellow-fever requirements depend on your itinerary and countries transited, particularly arrivals from risk countries; rules can change.</> },
  { category: 'Health Safety & Insurance', question: 'Are mosquito nets and insect protection provided?', answer: <>Most safari lodge rooms and tented camps provide screened accommodation and mosquito nets where appropriate. Pack a proven repellent, cover arms and legs after sunset, and keep doors zipped. Your camp team can advise on local conditions without replacing medical advice.</> },
  { category: 'Health Safety & Insurance', question: 'How safe is a Kenya safari?', answer: <>Professional safari travel is carefully managed: use reputable camps, listen to guides, remain in the vehicle unless invited out, and never walk alone after dark in unfenced areas. Keep valuables discreet in cities and use arranged transfers. Wildlife deserves distance and calm behaviour.</> },
  { category: 'Payments & Booking', question: 'Which payment methods do you accept?', answer: <>Collective African Tours & Safaris accepts Wise transfer, M-Pesa, bank transfer and credit card payments. Current instructions, charges and secure payment details are provided with your invoice; visit <A href="/payment-methods">payment methods</A> before sending funds.</> },
  { category: 'Payments & Booking', question: 'What deposit and balance are required?', answer: <>A deposit secures accommodation, permits and flights; the amount and balance due date appear in your tailored quotation because supplier terms vary. Gorilla permits and peak-season camps can require earlier or full payment. We do not treat a space as confirmed until supplier confirmation and cleared payment.</> },
  { category: 'Payments & Booking', question: 'How does booking confirmation work?', answer: <>After you approve the itinerary, we issue an invoice and payment instructions, place provisional services where possible, then confirm each lodge, transport and activity. You receive a written confirmation and pre-departure information. Contact info@catssafaris.com or +254 723 951 388 for status at any stage.</> },
  { category: 'Payments & Booking', question: 'What is your cancellation and refund policy?', answer: <>Cancellation charges depend on the notice period and non-refundable supplier costs, including permits, flights and some peak-date deposits. The exact schedule is supplied with your quotation and booking terms before payment. Notify us in writing immediately; we pursue recoverable refunds but cannot refund services already charged by suppliers.</> },
  { category: 'Payments & Booking', question: 'Can you plan honeymoon and anniversary safaris?', answer: <>Absolutely. We select romantic tented camps, private dinners, scenic flights, ballooning and Diani Beach or Zanzibar extensions while balancing privacy with strong wildlife viewing. Mention celebrations early: many properties offer thoughtful amenities, but these are subject to availability.</> },
  { category: 'Travel Documents & Visas', question: 'Do I need a Kenya visa?', answer: <>Most visitors need a Kenya electronic travel authorisation/visa arranged before travel. Apply only through <a href="https://www.evisa.go.ke" target="_blank" rel="noreferrer" className="text-[var(--golden-savannah)] underline hover:decoration-transparent">www.evisa.go.ke</a>; the stated fee is USD 50 plus a USD 1 service fee, subject to government change. Check passport validity, nationality rules and transit requirements yourself.</> },
  { category: 'Travel Documents & Visas', question: 'What travel documents should I carry?', answer: <>Carry a passport valid for at least six months beyond travel, visa/eTA approval where required, insurance certificate, flight details, emergency contacts and copies stored separately. Trekking permits and domestic-flight tickets are issued through your itinerary. Requirements are the traveller’s responsibility and may change.</> },
  { category: 'Travel Documents & Visas', question: 'What currency and money should I bring?', answer: <>Kenyan shillings (KES) are used locally; major hotels accept cards, while small tips and markets benefit from small US-dollar notes or KES. ATMs are common in Nairobi and larger towns but not in every park. Tell your bank before travel and avoid relying on a single card.</> },
  { category: 'Travel Documents & Visas', question: 'Should I buy a local SIM card?', answer: <>Safaricom has broad coverage and is the usual choice for calls, data and M-Pesa, although signal fades in remote reserves. Buy from an official outlet with your passport, or use an eSIM if compatible. Lodge WiFi should not be your sole connection.</> },
  { category: 'Travel Documents & Visas', question: 'How much should I tip on safari?', answer: <>Tipping is discretionary and based on service. As a useful guide, budget about USD 10 per guest per day for a dedicated safari guide, with separate camp staff gratuities often placed in a communal box. Small notes make distribution easy; ask us for current local guidance.</> },
  { category: 'Packing & Luggage', question: 'What should I pack for safari?', answer: <>Pack breathable neutral-colour layers, a fleece for dawn drives, closed walking shoes, hat, sunglasses, sunscreen, binoculars, camera and spare batteries. Include personal malaria medication if prescribed, a reusable bottle and a light rain layer. Avoid bright colours and camouflage-pattern clothing.</> },
  { category: 'Packing & Luggage', question: 'What luggage limits apply?', answer: <>For road safaris, 25–30kg per person is a practical guideline. Bush airlines commonly impose stricter limits and require soft-sided bags because aircraft holds are compact; your exact flight allowance prevails. Hard cases are inconvenient in Land Cruisers and should be avoided for fly-in routes.</> },
  { category: 'Packing & Luggage', question: 'Can you store excess luggage in Nairobi?', answer: <>Yes, we can help arrange luggage storage at our Nairobi office for items not needed on safari, subject to advance arrangement and space. Keep passports, money, medication, cameras and valuables with you. Label every bag and confirm collection timing before your return.</> },
  { category: 'Packing & Luggage', question: 'Is drinking water provided?', answer: <>Complimentary bottled or filtered drinking water is carried in our safari vehicles, and camps provide safe drinking water for guests. Bring a refillable bottle to reduce plastic waste. Use only advised drinking water and avoid dehydration during warm game drives or climbs.</> },
  { category: 'Family & Special Needs', question: 'Are family safaris suitable for children?', answer: <>Yes. We recommend private vehicles, family-friendly camps, manageable drive times and activities suited to attention spans. Children aged 0–10 (under 11 years) qualify for child rates where a supplier offers them; lodge minimum ages and room policies vary, especially for walking activities.</> },
  { category: 'Family & Special Needs', question: 'Can you cater for dietary requirements?', answer: <>Yes. Vegetarian, vegan, halal, gluten-free and allergy requirements can usually be accommodated when declared at booking. Remote camps plan supplies ahead, so detail allergies, severity and cross-contamination needs in writing. Carry critical medication and suitable emergency snacks.</> },
  { category: 'Family & Special Needs', question: 'Are safaris accessible for guests with limited mobility?', answer: <>We assess each guest individually and can choose accessible rooms, minimise transfers, reserve suitable vehicles and arrange assistance. Uneven ground, steps and small aircraft may limit some camps, but a rewarding Kenya safari is often possible with honest advance information about mobility equipment and support needs.</> },
  { category: 'Kenya Coast & Beach', question: 'Can I add Diani Beach to my safari?', answer: <>Diani Beach pairs beautifully with the Masai Mara, Amboseli or Tsavo: expect white sand, warm Indian Ocean water, dhow excursions and relaxed safari lodges by the sea. Reach it by flight to Ukunda or through Mombasa with road transfer; we tailor the right number of nights.</> },
  { category: 'Kenya Coast & Beach', question: 'Can you add Zanzibar to a Kenya safari?', answer: <>Yes. Zanzibar works well after Kenya or Tanzania, with flights typically routed via Nairobi, Mombasa or Kilimanjaro depending on season. We can combine Stone Town, spice history and beach stays, and coordinate luggage, flight buffers and entry rules for a seamless extension.</> },
  { category: 'Kenya Coast & Beach', question: 'When is the best time for a Kenya beach extension?', answer: <>January–March and July–October are popular for sunny beach time, while April–May can be wetter. The coast is warmer and more humid than Nairobi year-round. For diving, kitesurfing or marine-life priorities, ask us to match sea conditions and resort location to your dates.</> },
  { category: 'Nairobi National Park', question: 'Can I visit Nairobi National Park on a morning or afternoon tour?', answer: <>Yes. We run daily Nairobi National Park group tours in both AM and PM formats, subject to park access and minimum operational conditions. Morning drives favour cool active hours; afternoon tours suit arrivals or city schedules. Explore options at <A href="/kenya-safaris/nairobi-excursions">Nairobi excursions</A>.</> },
  { category: 'Nairobi National Park', question: 'Which animals live in Nairobi National Park?', answer: <>Against the city skyline, look for lions, black rhinos, giraffes, hippos, buffaloes, leopards, ostriches and warthogs, plus more than 400 bird species. There are no elephants in Nairobi National Park. Sightings are wild and never guaranteed, but the park is exceptional so close to the capital.</> },
  { category: 'Nairobi National Park', question: 'How long does a Nairobi National Park game drive take?', answer: <>Allow roughly 4–5 hours inside and around the park, plus collection time depending on your Nairobi hotel and gate traffic. A private drive offers flexible pace and photography stops; group tours run daily on set morning and afternoon schedules.</> },
  { category: 'Nairobi National Park', question: 'Where should I stay in Nairobi before safari?', answer: <>We recommend a hotel based on arrival hour and next-day logistics: an airport-area hotel for late JKIA arrivals, a Wilson Airport-area property for early bush flights, or central Karen/Westlands for sightseeing. We can coordinate a hotel shuttle and airport pickup; enquire at info@catssafaris.com or +254 723 951 388.</> },
  { category: 'Gorilla Trekking', question: 'What is gorilla trekking and where can I do it?', answer: <>Gorilla trekking is a guided hike to a habituated mountain-gorilla family in Uganda’s Bwindi/Mgahinga region or Rwanda’s Volcanoes National Park. Permits are limited, trekking can be steep and sightings involve one carefully managed hour with the gorillas. We build it into East Africa routes early.</> },
  { category: 'Gorilla Trekking', question: 'How fit do I need to be for gorilla trekking?', answer: <>Trails range from relatively short to several demanding hours through muddy, hilly forest at altitude. Porters are strongly recommended and support local livelihoods; walking sticks can help. Tell us about fitness or mobility before permits are secured so we can discuss suitable bases and expectations.</> },
  { category: 'Gorilla Trekking', question: 'What should I pack for gorilla trekking?', answer: <>Wear sturdy waterproof hiking boots, long trousers, long sleeves, gloves, rain jacket and gaiters; pack water, snacks and a dry bag. Flash photography is not permitted near gorillas. Your guide will brief distance, masks or health rules where required, and respectful viewing behaviour.</> },
  { category: 'Mountain Climbing', question: 'Can you arrange Mt Kilimanjaro and Mt Kenya climbing?', answer: <>Yes. We arrange guided <A href="/mountain-climbing">mountain climbing</A> programmes for Mt Kilimanjaro and Mt Kenya with route, acclimatisation, park fees, mountain crew and equipment guidance matched to experience. Kilimanjaro is in Tanzania; Mt Kenya adds technical options at higher peaks.</> },
  { category: 'Mountain Climbing', question: 'How long does it take to climb Mt Kilimanjaro?', answer: <>Most responsible Mt Kilimanjaro itineraries take 6–8 days, allowing acclimatisation rather than racing upward. A longer route usually improves summit odds. Training, altitude awareness, proper boots and travel insurance that explicitly covers high-altitude trekking are essential.</> },
  { category: 'Mountain Climbing', question: 'What safety preparation is needed for mountain climbing?', answer: <>Use qualified guides, build fitness in advance and choose an itinerary with acclimatisation days. Guides monitor altitude symptoms and carry appropriate emergency plans; descend immediately if instructed. Disclose medical conditions, obtain travel-clinic advice and ensure evacuation insurance covers the summit altitude and activity.</> },
];

const categories: Array<'All' | Category> = ['All', 'Planning Your Safari', 'Accommodation', 'Safari Vehicles & Transport', 'Wildlife & Game Drives', 'Health Safety & Insurance', 'Payments & Booking', 'Travel Documents & Visas', 'Packing & Luggage', 'Family & Special Needs', 'Kenya Coast & Beach', 'Nairobi National Park', 'Gorilla Trekking', 'Mountain Climbing'];

export default function FaqList() {
  const [selected, setSelected] = useState<'All' | Category>('All');
  const [open, setOpen] = useState<Set<number>>(() => new Set([0]));
  const visible = useMemo(() => faqs.map((faq, index) => ({ faq, index })).filter(({ faq }) => selected === 'All' || faq.category === selected), [selected]);
  const toggle = (index: number) => setOpen(current => { const next = new Set(current); next.has(index) ? next.delete(index) : next.add(index); return next; });
  return <section>
    <div className="mb-8 flex gap-2 overflow-x-auto pb-2" role="tablist" aria-label="FAQ categories">
      {categories.map(category => { const count = category === 'All' ? faqs.length : faqs.filter(faq => faq.category === category).length; const active = selected === category; return <button key={category} type="button" role="tab" aria-selected={active} onClick={() => setSelected(category)} className={`shrink-0 rounded-full border px-4 py-2 text-sm font-semibold transition ${active ? 'border-[var(--golden-savannah)] bg-[var(--golden-savannah)] text-white' : 'border-stone-200 bg-white text-[var(--forest-canopy)] hover:border-[var(--golden-savannah)]'}`}>{category} <span className="ml-1 opacity-80">({count})</span></button>; })}
    </div>
    <div className="space-y-7">
      {visible.map(({ faq, index }, position) => <div key={faq.question}>
        {selected === 'All' && (position === 0 || visible[position - 1].faq.category !== faq.category) && <h2 className="mb-3 font-playfair text-sm font-bold uppercase tracking-[0.16em] text-[var(--golden-savannah)]">{faq.category}</h2>}
        <article className="rounded-2xl border border-stone-200 bg-white">
          <button type="button" aria-expanded={open.has(index)} onClick={() => toggle(index)} className="flex w-full items-center justify-between gap-5 px-5 py-5 text-left font-semibold text-[var(--forest-canopy)] sm:px-7"><span>{faq.question}</span><span className="text-2xl font-normal leading-none text-[var(--golden-savannah)]" aria-hidden="true">{open.has(index) ? '−' : '+'}</span></button>
          <div className={`grid transition-[grid-template-rows] duration-300 ease-in-out ${open.has(index) ? 'grid-rows-[1fr]' : 'grid-rows-[0fr]'}`}><div className="overflow-hidden"><div className="px-5 pb-6 text-sm leading-7 text-stone-600 sm:px-7">{faq.answer}</div></div></div>
        </article>
      </div>)}
    </div>
    <aside className="mt-8 rounded-2xl bg-[var(--warm-ivory)] p-6 text-sm leading-7 text-stone-600">For tailored answers and current availability, contact Collective African Tours & Safaris at <a href="mailto:info@catssafaris.com" className="font-semibold text-[var(--golden-savannah)] underline hover:decoration-transparent">info@catssafaris.com</a> or <a href="tel:+254723951388" className="font-semibold text-[var(--golden-savannah)] underline hover:decoration-transparent">+254 723 951 388</a>. Follow current safari inspiration on <a href="https://www.facebook.com/CATSAFARISKENYA" target="_blank" rel="noreferrer" className="font-semibold text-[var(--golden-savannah)] underline hover:decoration-transparent">Facebook</a>.</aside>
  </section>;
}
