import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = { title: 'Safari Packing List for East Africa | C.A.T.S Safaris', description: 'A practical Kenya, Tanzania, Uganda and Rwanda safari packing list: clothing, camera gear, medicines, luggage and seasonal advice.', alternates: { canonical: '/travel-info/what-to-pack' } }

const essentials = [
  ['Clothing for the bush', 'Choose breathable khaki, olive, beige and other muted layers. Dawn game drives can feel close to 10°C, before afternoons become warm. Pack a fleece or light insulated layer, a waterproof shell, long trousers and long sleeves for bush walks. Avoid bright colours and blue or black, which can attract tsetse flies in some areas.'],
  ['Shoes & sun protection', 'Closed-toe walking shoes with grip suit most safari activities; relaxed sandals are useful around camp. Bring SPF 50+ sunscreen, a wide-brim hat and UV-protective sunglasses.'],
  ['Wildlife viewing & camera gear', 'Binoculars are transformative: 8x42 balances brightness and steadiness, while 10x42 gives more reach. A 200–400mm telephoto lens is excellent for wildlife photography. Carry spare batteries, memory cards, a charger and a dust-proof camera bag; keep valuable photography equipment in cabin baggage.'],
  ['Health & toiletries', 'Bring personal medication in original packaging, a basic first-aid kit, DEET-based insect repellent and any malaria prophylaxis advised by a qualified travel-health professional. Biodegradable toiletries and wet wipes are useful where water is limited.'],
  ['On the move', 'A compact daypack holds water, layers, camera gear and documents on game drives. Kenya and much of East Africa use Type G, UK-style plugs at 240V, though camps may have limited charging hours. A torch or headlamp is helpful after dark.']
]

export default function WhatToPackPage() { return <main className="bg-[var(--warm-ivory)] text-[var(--forest-canopy)]"><section className="bg-[var(--forest-canopy)] pt-40 pb-20 px-6"><div className="mx-auto max-w-5xl"><p className="text-[var(--golden-savannah)] uppercase tracking-[0.22em] text-sm">Travel information</p><h1 className="font-playfair mt-4 text-5xl md:text-6xl text-white">What to Pack for Safari</h1><p className="mt-6 max-w-3xl text-lg text-white/80">A considered East Africa safari packing list for unhurried mornings, dusty tracks and unforgettable wildlife encounters.</p></div></section><section className="mx-auto max-w-5xl px-6 py-16 space-y-10 leading-8"><p>Pack light, practical and in layers. The best safari packing list serves Kenya’s savannahs, Tanzania’s plains, Uganda’s forests and Rwanda’s higher, cooler terrain without filling every corner of your bag.</p><div className="grid gap-6 md:grid-cols-2">{essentials.map(([title, copy]) => <article key={title} className="bg-[var(--savannah-dust)] p-7"><h2 className="font-playfair text-3xl">{title}</h2><p className="mt-3">{copy}</p></article>)}</div><article><h2 className="font-playfair text-3xl">Documents & luggage</h2><p className="mt-3">Carry your passport, relevant visa or electronic travel authorisation confirmation, travel-insurance details, return itinerary and vaccination card. A Yellow Fever certificate may be required when arriving from a risk country. Soft-sided luggage is essential for many bush flights, where the usual total limit is 15kg including hand luggage; see our baggage policy before finalising your bag. Hard cases are generally suitable for a road safari.</p></article><article><h2 className="font-playfair text-3xl">What not to bring</h2><p className="mt-3">Leave bright clothing, strong perfume and excessive luggage at home. Drones are prohibited or tightly controlled in most national parks and reserves; never pack or fly one without explicit written authorisation. Avoid camouflage clothing, which can be restricted for civilians in some African countries.</p></article><div className="grid gap-6 md:grid-cols-2"><article><h2 className="font-playfair text-3xl">June–October dry season</h2><p className="mt-3">Mornings and evenings can be crisp, vegetation is thinner and dusty conditions are common. Prioritise a warm layer, lip balm, eye protection and a camera cover.</p></article><article><h2 className="font-playfair text-3xl">November–May green season</h2><p className="mt-3">Expect lush landscapes, occasional rain and more insects. Add a lightweight waterproof jacket, quick-drying clothing and robust insect protection. Roads can be muddy, so shoes with traction matter.</p></article></div><div className="border-t border-[var(--golden-savannah)] pt-8"><Link href="/contact" className="inline-block rounded-full bg-[var(--golden-savannah)] px-6 py-3 font-semibold">Ask a safari specialist</Link></div></section></main> }
